import {
  AlertCircle,
  AlertTriangle,
  AlignJustify,
  ArrowUp,
  Calendar,
  ChartArea,
  ChartNoAxesColumn,
  CheckCircle,
  CirclePlus,
  Component,
  Droplets,
  Gauge,
  HelpCircle,
  History,
  Loader,
  LogIn,
  LogOut,
  LucideIcon,
  TrendingDown,
  TrendingUp,
  Wrench,
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
  component: Component,
  chart: ChartArea,
  history: History,
  circlePlus: CirclePlus,
  loader: Loader,
  calendar: Calendar,
  droplets: Droplets,
  alignJustify: AlignJustify,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  avg: ChartNoAxesColumn,
  wrench: Wrench,
  helpCircle: HelpCircle,
  checkCircle: CheckCircle,
  alertTriangle: AlertTriangle,
  alertCircle: AlertCircle,
  gauge: Gauge,
  arrowUp: ArrowUp,
  logout: LogOut,
  login: LogIn,
}
