export {
  avgSpendsInMonth,
  createRecord,
  deleteRecordById,
  getLastYearWithData,
  getMonthsSpendsByYear,
  getRecordById,
  getRecordsCountByMonth,
  getSpendsByMonthYear,
  getSpendsByYear,
  getTotalSpends,
  getYears,
  updateRecordById,
} from './api'
export {
  AVARAGE_SPENDS_IN_MONTH,
  RECORD_BASE_QUERY_KEY,
  getRecordTagsLabels,
  TOTAL_SPENDS,
  useGetLatestRecordByTag,
  useGetMonthsSpends,
  useGetRecordById,
  useGetRecords,
  useGetRecordsCountByMonth,
  useGetSpendsByMonthYear,
  useGetSpendsByYear,
  useUpdateRecordById,
  YEARS_WITH_DATA,
} from './lib'
export {
  additionalSpend,
  additionalSpendsSchema,
  createRecordFormSchema,
  createRecordSchema,
  recordSchema,
  updateRecordSchema,
  type AdditionalSpendSchema,
  type ComponentsSchema,
  type CreateRecordFormSchema,
  type RecordSchema,
  type RecordsComponentWithData,
  type CreateAdditionalSpendSchema,
} from './model'
export { CreateRecordDialog } from './ui/create-record-dialog'
