import { RecordTags } from '@prisma/client'

export const maintenanceIntervals: Record<RecordTags, number> = {
  [RecordTags.ENGINE_OIL_CHANGE]: 7000,
  [RecordTags.OIL_FILTER_REPLACEMENT]: 7000,
  [RecordTags.ENGINE_AIR_FILTER_REPLACEMENT]: 15000,
  [RecordTags.SPARK_PLUGS_REPLACEMENT]: 30000,
  [RecordTags.FUEL_FILTER_REPLACEMENT]: 20000,
  [RecordTags.TIMING_BELT_REPLACEMENT]: 60000,
  [RecordTags.ROLLERS_AND_PUMP_REPLACEMENT]: 60000,

  [RecordTags.GEARBOX_OIL_CHANGE]: 40000,

  [RecordTags.BRAKE_PADS_REPLACEMENT]: 25000,
  [RecordTags.BRAKE_DISKS_REPLACEMENT]: 80000,

  [RecordTags.BALL_BEARINGS_REPLACEMENT]: 70000,
  [RecordTags.FRONT_ARM_SILENT_BLOCKS_REPLACEMENT]: 60000,
  [RecordTags.REAR_ARM_SILENT_BLOCKS_REPLACEMENT]: 60000,
  [RecordTags.FRONT_SHOCK_ABSORBERS_REPLACEMENT]: 70000,
  [RecordTags.REAR_SHOCK_ABSORBERS_REPLACEMENT]: 70000,

  [RecordTags.CABIN_FILTER_REPLACEMENT]: 15000,

  [RecordTags.POWER_STEERING_FLUID_CHANGE]: 60000,
}
