import { RecordTags } from '@prisma/client'

export const getRecordTagsLabels = (
  t: (key: string) => string,
): Record<RecordTags, string> => ({
  [RecordTags.ENGINE_OIL_CHANGE]: t('ENGINE_OIL_CHANGE'),
  [RecordTags.OIL_FILTER_REPLACEMENT]: t('OIL_FILTER_REPLACEMENT'),
  [RecordTags.GEARBOX_OIL_CHANGE]: t('GEARBOX_OIL_CHANGE'),
  [RecordTags.BRAKE_PADS_REPLACEMENT]: t('BRAKE_PADS_REPLACEMENT'),
  [RecordTags.BRAKE_DISKS_REPLACEMENT]: t('BRAKE_DISKS_REPLACEMENT'),
  [RecordTags.ENGINE_AIR_FILTER_REPLACEMENT]: t(
    'ENGINE_AIR_FILTER_REPLACEMENT',
  ),
  [RecordTags.CABIN_FILTER_REPLACEMENT]: t('CABIN_FILTER_REPLACEMENT'),
  [RecordTags.BALL_BEARINGS_REPLACEMENT]: t('BALL_BEARINGS_REPLACEMENT'),
  [RecordTags.FRONT_ARM_SILENT_BLOCKS_REPLACEMENT]: t(
    'FRONT_ARM_SILENT_BLOCKS_REPLACEMENT',
  ),
  [RecordTags.REAR_ARM_SILENT_BLOCKS_REPLACEMENT]: t(
    'REAR_ARM_SILENT_BLOCKS_REPLACEMENT',
  ),
  [RecordTags.FRONT_SHOCK_ABSORBERS_REPLACEMENT]: t(
    'FRONT_SHOCK_ABSORBERS_REPLACEMENT',
  ),
  [RecordTags.REAR_SHOCK_ABSORBERS_REPLACEMENT]: t(
    'REAR_SHOCK_ABSORBERS_REPLACEMENT',
  ),
  [RecordTags.SPARK_PLUGS_REPLACEMENT]: t('SPARK_PLUGS_REPLACEMENT'),
  [RecordTags.FUEL_FILTER_REPLACEMENT]: t('FUEL_FILTER_REPLACEMENT'),
  [RecordTags.TIMING_BELT_REPLACEMENT]: t('TIMING_BELT_REPLACEMENT'),
  [RecordTags.ROLLERS_AND_PUMP_REPLACEMENT]: t('ROLLERS_AND_PUMP_REPLACEMENT'),
  [RecordTags.POWER_STEERING_FLUID_CHANGE]: t('POWER_STEERING_FLUID_CHANGE'),
})
